### PR TITLE
Add useSocket hook

### PR DESCRIPTION
**Pull request by caseybaggz**
Let me know if there is anything else you need or see missing from this example?

### CODE REVIEW

**Comment by gragland** [comment]
@caseybaggz Would you mind adding a CodeSandbox demo and maybe some more code comments? Don't have a lot of experience with WebSockets so not totally sure what's going on at first glance. I think a demo would help though.

**Comment by caseybaggz** [comment]
@gragland sure thing!

**Comment by caseybaggz** [comment]
@gragland I added the comments and sandbox. The sandbox still needs a little bit of work due to WS requiring a socket server to be up and running - thus, I'm trying to connect it to use a tool for right now. 

Give me a couple of more days and this should be ready. 👍

**Comment by caseybaggz** [comment]
Alrighty @gragland ! So, so, so, so, sorry for they delay. It was crunch time for a milestone we were approaching. Finally got the sandbox up and running with comments.

Let me know if you need anything else?

**Comment by caseybaggz** [comment]
@gragland just checking in to see if you spotted anything that needs an update in order to be good for the merge?

**Pull request closed without merging**
