### PR TITLE
Add Typescript types definition for all hooks

### PR DESCRIPTION
**Pull request by toystars**
Thanks for the awesome library. Saves lots of time from writing these hooks from scratch. I was a little bit disappointed there weren't Typescript type definitions and had to add declarations for the few hooks I am currently using. So I added types for all the hooks in the library (excluding the experimental hooks).

### CODE REVIEW

**Comment by joaopcm** [comment]
Please! You're our hero :)

**Review by joaopcm — APPROVED** [review]
Congrats! This is not only a PR, it's an art! ⭐ 

---

external-content duckduckgo com

> “I once saw him kill three men in a bar... With a pencil.”

**Review by ariesclark — APPROVED** [review]

**Comment by fionnachan** [comment]
would love to see this in a release soon!! <3
hope the maintainers can merge it asap

**Comment by rlesniak** [comment]
wen release

**Comment by Waryen** [comment]
Nice job! But I have a proposal, why not rewrite the hooks with TypeScript? I believe this could bring a better DX, I'm open to work on it if this is wanted

**Comment by ariesclark** [comment]
> Nice job! But I have a proposal, why not rewrite the hooks with TypeScript? I believe this could bring a better DX, I'm open to work on it if this is wanted

I feel like this is more work than it's worth right now, this solution is a stop-gap solution in the meanwhile and it should be merged.

**Comment by Waryen** [comment]
> > Nice job! But I have a proposal, why not rewrite the hooks with TypeScript? I believe this could bring a better DX, I'm open to work on it if this is wanted
> 
> I feel like this is more work than it's worth right now, this solution is a stop-gap solution in the meanwhile and it should be merged.

I agree, this should be merged first in the meantime.

**Comment by ariesclark** [comment]
Or consider using https://usehooks-ts.com/.

**Comment by Waryen** [comment]
> Or consider using https://usehooks-ts.com/.

It seems to be a good alternative with TS indeed

**Comment by toystars** [comment]
> Nice job! But I have a proposal, why not rewrite the hooks with TypeScript? I believe this could bring a better DX, I'm open to work on it if this is wanted

I 100% agree this would be the ideal approach but I wanted something quick to start with just as @ariesclark highlighted as well. I can take some time over the weekend to re-write the hooks with Typescript.

**Review by Soib — APPROVED** [review]

**Comment by AmagiDDmxh** [comment]
wen merge ser?

**Comment by tylermcginnis** [comment]
Sorry for the delay everyone. Merged. Thank you @toystars!

**Pull request merged**
