### PR TITLE
useKonamiCode.md

### PR DESCRIPTION
**Pull request by chrislaughlin**
Adding the useKonamiCode hook

### CODE REVIEW

**Comment by vanillajonathan** [comment]
When using a `switch` statement, you don't need `break` statements when using `return` statements because the return statement will break further execution.

**Comment by chrislaughlin** [comment]
@vanillajonathan updated the switch statement, thanks

**Comment by vanillajonathan** [comment]
@chrislaughlin The text says that the code is stored for 3 seconds but the code has a 10isecond timeout.

@tylermcginnis Close without comment? No merge?

**Comment by tylermcginnis** [comment]
@vanillajonathan We've completely revamped the site and all the hooks. Launching it in the next few weeks and don't want to start with a bunch of out of date issues/PRs.

**Comment by vanillajonathan** [comment]
Alright, but I am not sure they're not relevant for the new website just because the issue and PRs might be old.

**Pull request closed without merging**
