### PR TITLE
add useInterval hook

### PR DESCRIPTION
**Pull request by escaton**

### CODE REVIEW

**Comment by gragland** [comment]
Thanks! I found this other solution you proposed to be pretty easy to understand: https://github.com/facebook/react/issues/14543#issuecomment-452676760

Are there any downsides to that solution vs. the one in this pull request?

**Comment by escaton** [comment]
Let me highlight the problem: we need to execute some code in cycle with constant time interval. Similar to what `setInterval` does. And that code depends on component state.
So the problem here 
```js
const [state, setState] = useState(0)
useEffect(() => {
  const id = setInterval(
    () => { console.log(state) } // always logs "0"
  , 1000)
  return () => clearInterval(id)
}, [])
```
is that the first state is trapped in interval closure.
Hooks docs told us: if our effect depends on something from outside, this something should be in second argument.
```js
useEffect(() => {
  const id = setInterval(
    () => { console.log(state) } // works almost as expected
  , 1000)
  return () => clearInterval(id)
}, [state])
```
Looks fine, but now it doesn't meet the criteria of constant time interval between calls. Because every time `state` changes `setInterval` restarts.

Looking back there was no such problem before: using class components we have `state` coupled to instance and `this` always have reference to actual state value.
```js
componentDidMount() {
  setInterval(
    () => { console.log(this.state) } // "unboxing" state gives actual value every time
  , 1000)
}
```
So how it could be solved?

The first approach is pretty straight. We need something that will hold the reference to `state` like `this` in class components does it.
While there is still component's own `this` in functional components (except those created with arrow function) React doesn't keep there anything useful for us. Instead we have`useRef` so lets actually use it :)
```js
const [state, setState] = useState()
const stateRef = useRef(state)
useEffect({
  const id = setInterval(
    () => { console.log(stateRef.current) } // still logs "0" every time
  , 1000)
  return () => clearInterval(id)
}, []) // no state here
```
Now we have to _update_ this reference every time state changes. 
And here is the question: is reference mutation a side effect? Honest answer would be "yes".
If so than we need to wrap it in another `useEffect`:
```js
const stateRef = useRef(state)
useEffect(
  () => stateRef.current = state,
  [state]
)
useEffect({
  const id = setInterval(
    () => { console.log(stateRef.current) } // works nicely
  , 1000)
  return () => clearInterval(id)
}, []) // neither state nor stateRef here
```
Ok, now we've got working solution. Is everything fine? Almost.
Now we have implicit dependency between two effects. And what's worse: there is a lag between `state` and `stateRef.current` changes. That means that we can't use `stateRef` anywhere but in subsequent effects (depending on effects execution order)
```js
const stateRef = useRef(state)
useEffect(
  () => stateRef.current = state,
  [state]
)
useEffect({
  const id = setInterval(
    () => { console.log(stateRef.current === state) }  // true
  , 1000)
  return () => clearInterval(id)
}, [])
console.log(stateRef.current === state) // true? only until setState(...) will be called anywhere
```
So there are still issues. What if we suppose that mutating reference outside of effect is... _acceptable_?
Well it turns out that then we will achieve almost same behavior as in class components.
 ```js
const stateRef = useRef(state)
stateRef.current = state;
useEffect({
  const id = setInterval(
    () => { console.log(stateRef.current === state) }  // true
  , 1000)
  return () => clearInterval(id)
}, [])
console.log(stateRef.current === state) // obviously always true :)
```
I could finish here, but i feel like this is not ideal, at least until react team told that this is ok.

And there are at least two more idiomatic solutions :)
The first is in this PR and its about refactoring effect to make it tolerant to restart. No indirect `useRef` usage, no implicit dependencies on other effects or their execution order. Just swap `setInterval` with `setTimeout` and adjust timeouts.

The other possible solution is about turning original problem in the following way: what we actually want is two separate effects. One is timer tick, the other is tick body.
```js
const [tick, setTick] = useState(0)

useEffect(() => {
  const id = setInterval(() => {
    setTick(t => t+1)
  }, 5000)
  return () => clearInterval(id)
}, [])

useEffect(() => {
  console.log(state) // always actual state
}, [tick]) // although state is not here
```
In my eyes it looks very nice although it causes rerenders every 5 seconds.

What would you prefer? :)

**Comment by gragland** [comment]
@escaton Thanks for breaking that down for me! I'd be interested to hear from the React team if mutating the reference outside of the effect is acceptable in this case. I sure find it easier to quickly understand, but of course don't want to recommend an anti-pattern. Otherwise the last solution will probably work. Will think on this some more and see if I can get any input from them.

**Comment by Yurickh** [comment]
Dan wrote a blogpost on this exact topic: https://overreacted.io/making-setinterval-declarative-with-react-hooks/

**Comment by gragland** [comment]
@Yurickh Thanks! Yeah that settles that then. @escaton Seems really close to what you have. I think I'd like to post it exactly how Dan does it so that I can just link over to his blog post for the full explanation.

**Comment by escaton** [comment]
Of course

**Comment by gragland** [comment]
Closing because explaining how to make setInternal declarative is too lengthy for the format of this blog. I'll leave that to Dan :)

**Pull request closed without merging**
