### PR TITLE
Add initial state for useAsync hook

### PR DESCRIPTION
**Pull request by bozheville**
I suggest adding a new export for `useAsnyc`: `initial` that is true before the first `execute`.

`initial` state is vital to understand the reason for an empty value. Without `initial` state developer has to implement additional logic to determine what is a correct message for user: "Greetings" or "Sorry, nothing found"

### CODE REVIEW

**Comment by bozheville** [comment]
Hey @gragland,

here's the actual change 

```diff
function App() {
-  const { execute, pending, value, error } = useAsync(myFunction, false);
+  const { execute, initial,  pending, value, error } = useAsync(myFunction, false);

  return (
    <div>
+     {initial && <div>Start your journey by clicking a button</div>}
      {value && <div>{value}</div>}
      {error && <div>{error}</div>}
      <button onClick={execute} disabled={pending}>
        {!pending ? 'Click me' : 'Loading...'}
      </button>
    </div>
  );
}

const useAsync = (asyncFunction, immediate = true) => {
  const [pending, setPending] = useState(false);
+ const [initial, setInitial] = useState(true);
  const [value, setValue] = useState(null);
  const [error, setError] = useState(null);

  const execute = useCallback(() => {
    setPending(true);
    setValue(null);
+   setInitial(false);
    setError(null);
    return asyncFunction()
      .then(response => setValue(response))
      .catch(error => setError(error))
      .finally(() => setPending(false));
  }, [asyncFunction]);

  useEffect(() => {
    if (immediate) {
      execute();
    }
  }, [execute, immediate]);

- return { execute, pending, value, error };
+ return { execute, initial, pending, value, error };
};
```

**Comment by gragland** [comment]
Thanks for this pull request! What do you think about adding `status` instead with the possible values `idle` (same as your `initial`), `pending`, `error`, and `success`? I've been using [react-query](https://react-query.tanstack.com/docs/api#usequery) lately and this is how they do it, which I quite like.

**Comment by bozheville** [comment]
Sounds reasonable. I'll replace `initial` and `pending` with `status`.

Also, what do you think about adding TypeScript support? Do you plan to update hooks with a TS version, additionally to JavaScript?

**Comment by gragland** [comment]
Thanks! I don't use TypeScript myself so wasn't planning on it, but happy to link out to a gist for any recipe and include that in the links section under a post. If people find this valuable, I could see in the future adding a "Show Typescript" option to toggle any recipe to the TS version.

**Pull request merged**
