### PR TITLE
convert email and index page components to use hooks; add basic email validation

### PR DESCRIPTION
**Pull request by trblackw**
I noticed that a couple of the core components were still using constructor syntax/class-based react so I converted them to use hooks. I also added a utility function to validate the email input before subscribing. I intend to look into helping you out with the search functionality, if you don't mind of course. Sick project man!

### CODE REVIEW

**Comment by gragland** [comment]
Hey, thanks so much for doing this! Would you mind adding a comment in `utils.js` linking to where you found the email validation regex (or maybe we should pull in a dependency from npm?). Just want to make sure no valid emails get rejected. Also seeing an issue with the pagination links now where next/prev are no longer buttons. Help with search would be great. I didn't originally add search because I couldn't decide where to put it in the UI, but open to any ideas or pull requests for that.

**Comment by trblackw** [comment]
@gragland The regex came from [this popular SO post](https://stackoverflow.com/questions/46155/how-to-validate-an-email-address-in-javascript). I always hesitate to add an entire package for such a singular goal, but I understand in this case you want it to be really effective. I've played around with it on tools like [RegexPal](https://www.regexpal.com/) and found it to work for every variation of an email that I could think of. 
Screen Shot 2019-05-06 at 8 27 22 AM

Also, as far as the pagination links go, I believe my intent with creating the `PaginationPrevious` and `PaginationNext` components to either render an `<a href="#"></a>` or a `<Link />` element was based on your todo comment ("Temp hack to prevent clicking TODO: Render a link without a href instead") but maybe I misunderstood the goal there. 

As far as the search functionality goes, I think that'd be fun to implement. I'll play around with it in my spare time this week and let you know how it goes. This is an awesome project man!

**Comment by trblackw** [comment]
@gragland I actually had a minute this morning before work and implemented some basic search functionality based solely on the titles of the hooks (I left your previous attempt commented out below). I also reverted the pagination links back to the way they were, my bad on that.

**Comment by gragland** [comment]
@trblackw Had some more time to think about validation. I'm thinking we should skip email validation and rely on built-in validation of `input type="email"`, which should catch common things like leaving off the tld. Other typos will commonly still be valid emails, so no perfect solution. Inclined to leave it out for now.

For search we're going to need to include posts from other pages (right now just two pages). Looks like right now it's just filtering on the current page. Haven't had time to think about the best way to do this with Gatsby. One option might be to have `gatsby-node.js` build a json file of all posts and use https://www.gatsbyjs.org/docs/adding-search-with-js-search/, but maybe there's a simpler way..

Would you mind doing a new commit that is just the "convert email and index page components to use hooks" part and I can get that merged asap?

**Comment by trblackw** [comment]
@gragland I didn't even think about the pageContext when implementing search functionality. Duh. Alright I reverted everything back to my initial changes and removed the email validation. For now, a lot of it is commented out, we can do clean up once we figure out the search functionality.

**Comment by gragland** [comment]
Great! Would you mind doing a fresh pull request that just contains the hook changes?

**Pull request closed without merging**
