### PR TITLE
converted useMemoCompare to typescript

### PR DESCRIPTION
**Pull request by nikasepiskveradze**
This code is not very concrete about it's use case, so there is no need for many explicit types, Typescript type inference is fine here.

### CODE REVIEW

**Comment by nikasepiskveradze** [comment]
@gragland Hi could you review and merge it? It's ready to be merged

**Comment by gragland** [comment]
> @gragland Hi could you review and merge it? It's ready to be merged

Hey, sorry but I'm no longer running this project. @tylermcginnis and the [github.com/uidotdev](https://github.com/uidotdev) team have taken things over. Not sure on their plans for the site, but they are the right people to talk to going forward :)

**Comment by tylermcginnis** [comment]
👋 lots of plans but not making any moves right now. We have a big launch coming in the next few weeks and after that we're going to put some time into useHooks and we'll address this PR then. Sorry for the delay!

**Comment by nikasepiskveradze** [comment]
@tylermcginnis Hi, is there some updates about this project?

**Comment by tylermcginnis** [comment]
Yes, we've rebuilt the site and all the hooks. Launching it in the next few weeks.

**Pull request closed without merging**
