### PR TITLE
Add ts hooks support

### PR DESCRIPTION
**Pull request by bozheville**
Hey @gragland,

Here's my proposal for adding TypeScript support. 

This is an entirely soft change, that adds a button "View in TypeScript/JavaScript" for hooks with definned `tsCode` field.

image

if you accept this approach, I will start updating hooks. There is one sample hook for now - `useAsync`

### CODE REVIEW

**Comment by gragland** [comment]
Awesome! Love this and happy to merge. My only nitpick would be to keep the TS version as similar as possible (hook usage at the top, same order of imports, etc) so it's easier to see what's changing when toggling between.

**Comment by bozheville** [comment]
Completely agree. I updated my last commit

**Comment by gragland** [comment]
Thanks! This is now live. Looking forward to seeing more :)

**Comment by trblackw** [comment]
@bozheville Can you share with me your strategy to converting your TS versions to markdown? Are you just using an external markdown editor/converter? Trying to figure out the best approach.

**Comment by gragland** [comment]
@trblackw Right now the code is escaped and then stored in the markdown frontmatter (not ideal and something [I'd like to fix](https://github.com/gragland/usehooks/issues/1)). So generally you'd just want to grab the non-TS code version, unescape it (here's an [online tool](https://www.freeformatter.com/json-escape.html)), work on it in your own editor, then escape it before pasting it back in under the frontmatter `tsCode` key. That's my process, although maybe @bozheville has a better answer.

**Comment by bozheville** [comment]
@trblackw, I use an awful primitive and long manual way. I paste code into an empty file in VSCode and replace `\n` with `\\r\\n`. I decided that looking for a better way will take more time than converting everything this way

**Pull request merged**
