### PR TITLE
Impliment media query based dark mode for site

### PR DESCRIPTION
**Pull request by petercr**
This PR contains the basics changes needed for issue #102 

I did _ask_ in #102 if you wanted me to include an icon for switching back and forth, but I never heard back on that.
So I just went ahead and use some CSS variables and `prefers-color-scheme` media queries to handle it. 

Let me know if you want to change anything, but I think it looks pretty good 😎 
Definitely easier on the 👀 

firefox_CdPWghqf1c

### CODE REVIEW

**Comment by petercr** [comment]
I'm not sure why the deploy would have failed 🤷🏻‍♂️ since I basically just changed CSS.

I will go ahead and try to deploy the site myself, and see if that sheds any light on the error.

**Comment by petercr** [comment]
Hey 👋🏻 any chance I could get you to add the label `Hacktoberfest` to this PR?

Apparently this year you need that for PRs to count towards it.

Thanks 🙏🏻

**Comment by vitaly-zdanevich** [comment]
Why closed?

**Comment by tylermcginnis** [comment]
We've completely revamped the site and all the hooks. We're launching it in the next few weeks and don't want to start with a bunch of out of date issues/PRs.

**Comment by petercr** [comment]
Great thanks so much for letting me know, and good luck with the new site 👍

**Pull request closed without merging**
